# Generated by Django 5.0.6 on 2024-05-27 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de email')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('biografia', models.CharField(max_length=500)),
                ('foto', models.CharField(max_length=20000)),
                ('Nascimento', models.DateField()),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioAutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bibliotecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioBibliotecario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=400)),
                ('n_paginas', models.IntegerField()),
                ('formato', models.CharField(choices=[('E', 'Ebook'), ('F', 'Fisico')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Aprovado'), ('C', 'Cancelado'), ('P', 'Pendente')], default='P', max_length=10)),
                ('n_edicao', models.IntegerField()),
                ('dataPub', models.DateField()),
                ('valor_livro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capa', models.CharField(max_length=1000)),
                ('estrela', models.IntegerField()),
                ('estoque', models.IntegerField()),
                ('autor_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LivroAutor', to='app.autor')),
                ('categoria_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CategoriaLivro', to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_pegou', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioEmprestimo', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ManyToManyField(related_name='LivrosEmprestimo', to='app.livros')),
            ],
        ),
    ]
