# Generated by Django 5.0.6 on 2024-06-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='n_paginas',
            new_name='N_paginas',
        ),
    ]
