# Generated by Django 5.0.6 on 2024-06-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_n_paginas_livros_n_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='capa',
            field=models.TextField(),
        ),
    ]
