# Generated by Django 5.0.6 on 2024-06-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_livros_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
